"""Add auto_pay and UserAchievement

Revision ID: 9a0c8c32bfec
Revises: 03d576a18057
Create Date: 2026-08-05 17:01:03.583916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a0c8c32bfec'
down_revision: Union[str, Sequence[str], None] = '03d576a18057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('achievement_code', sa.String(length=100), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_achievements_telegram_id'), ['telegram_id'], unique=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_pay', sa.Boolean(), nullable=False))

    # Removed transaction and users alters to avoid unnamed constraint issues

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed downgrades for transactions and users

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('auto_pay')

    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_achievements_telegram_id'))

    op.drop_table('user_achievements')
    # ### end Alembic commands ###
